/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import EkranIslemleri.OgrenciOlusturmaEkraniIslemleri;
import OgrenciKursSinavSonucu.Ogrenci;
import SQLIslemleri.DBIslemleri;
import javax.swing.JOptionPane;

/**
 *
 * @author ocak
 */
public class OgrenciOlusturmaUI extends javax.swing.JFrame {

    /**
     * Creates new form OgrenciOlustur
     */
    
    DBIslemleri dbIslemi;
    OgrenciOlusturmaEkraniIslemleri ogrenciOlusturmaEkraniIslemleri ; 
    
    private final String veriTabani = "kursprojesiveritabani";
    
    public OgrenciOlusturmaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldOgrenciTelefon = new javax.swing.JTextField();
        jTextFieldOgrenciTamAd = new javax.swing.JTextField();
        jTextFieldOgrenciNumarasi = new javax.swing.JTextField();
        jTextFieldOgrenciEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonOgrenciEkle = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jTextFieldOgrenciTelefon.setBackground(new java.awt.Color(255, 255, 51));
        jTextFieldOgrenciTelefon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefon Numarası", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jTextFieldOgrenciTamAd.setBackground(new java.awt.Color(255, 255, 51));
        jTextFieldOgrenciTamAd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Öğrenci Ad-Soyad", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jTextFieldOgrenciNumarasi.setBackground(new java.awt.Color(255, 255, 51));
        jTextFieldOgrenciNumarasi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Öğrenci Numarası", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jTextFieldOgrenciEmail.setBackground(new java.awt.Color(255, 255, 51));
        jTextFieldOgrenciEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jButtonOgrenciEkle.setBackground(new java.awt.Color(255, 255, 51));
        jButtonOgrenciEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addUser.png"))); // NOI18N
        jButtonOgrenciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciEkleActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-button (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonOgrenciEkle)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOgrenciEkle)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldOgrenciEmail)
                    .addComponent(jTextFieldOgrenciNumarasi)
                    .addComponent(jTextFieldOgrenciTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jTextFieldOgrenciTamAd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jTextFieldOgrenciNumarasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldOgrenciTamAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldOgrenciEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldOgrenciTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOgrenciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciEkleActionPerformed
        
        Ogrenci ogrenci;
        
        ogrenciOlusturmaEkraniIslemleri = new OgrenciOlusturmaEkraniIslemleri(jTextFieldOgrenciNumarasi,jTextFieldOgrenciTamAd,jTextFieldOgrenciEmail,jTextFieldOgrenciTelefon);
        
        dbIslemi = new DBIslemleri(veriTabani);
        
        boolean sorun = ogrenciOlusturmaEkraniIslemleri.uyariMesajiOlustur();
        
        boolean sonuc;
        
        System.out.println(sorun);
        
        if(sorun == true){
            
            JOptionPane.showMessageDialog(this,ogrenciOlusturmaEkraniIslemleri.getMesaj(),"Uyarı", 1);
            
        }else{
            
            ogrenci = ogrenciOlusturmaEkraniIslemleri.ogrenciOlustur();
            
            sonuc = dbIslemi.kullaniciOlustur(ogrenci);
     
            if(sonuc == true){
               
               JOptionPane.showMessageDialog(this,ogrenci.getTamAd()+" başarıyla oluşturuldu.","Bilgilendirme", 1);
               
               jTextFieldOgrenciNumarasi.setText("");
               jTextFieldOgrenciTamAd.setText("");
               jTextFieldOgrenciEmail.setText("");
               jTextFieldOgrenciTelefon.setText("");
               
                
            }else{
                
                 JOptionPane.showMessageDialog(this,"Öğrenci oluşturulamadı.","Bilgilendirme", 1);
           
            }
        }
 
    }//GEN-LAST:event_jButtonOgrenciEkleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        SonuclarUI sonuclarUI = new SonuclarUI();
        
        sonuclarUI.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgrenciOlusturmaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgrenciOlusturmaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgrenciOlusturmaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgrenciOlusturmaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OgrenciOlusturmaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonOgrenciEkle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldOgrenciEmail;
    private javax.swing.JTextField jTextFieldOgrenciNumarasi;
    private javax.swing.JTextField jTextFieldOgrenciTamAd;
    private javax.swing.JTextField jTextFieldOgrenciTelefon;
    // End of variables declaration//GEN-END:variables
}
