/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import EkranIslemleri.SonucOlusturmaEkraniIslemleri;
import OgrenciKursSinavSonucu.SinavSonucu;
import SQLIslemleri.DBIslemleri;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ocak
 */
public class SinavSonucuEklemeUI extends javax.swing.JFrame {

   
    DBIslemleri dbIslemleri;
    
    private final String veriTabani= "kursprojesiveritabani";
    
    ArrayList<Integer> ogrenciler = new ArrayList<>();
    ArrayList<String> kurslar = new ArrayList<>();
    
    private DefaultComboBoxModel ogrenciComboBoxModel;
    private DefaultComboBoxModel kursComboBoxModel;
    
    SonucOlusturmaEkraniIslemleri sonucOlusturmaEkraniIslemleri;
    
    public SinavSonucuEklemeUI() {
        initComponents();
        initComboBoxs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxOgrenci = new javax.swing.JComboBox<>();
        jComboBoxKurs = new javax.swing.JComboBox<>();
        jSpinnerSinavSonucu = new javax.swing.JSpinner();
        jButtonSonucEkle = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lütfen bir sınav sonucu giriniz:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 51, 51))); // NOI18N

        jComboBoxOgrenci.setBackground(new java.awt.Color(255, 255, 0));

        jComboBoxKurs.setBackground(new java.awt.Color(255, 255, 51));

        jSpinnerSinavSonucu.setModel(new javax.swing.SpinnerNumberModel(50, 1, 100, 1));
        jSpinnerSinavSonucu.setValue(50);

        jButtonSonucEkle.setBackground(new java.awt.Color(255, 51, 0));
        jButtonSonucEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check.png"))); // NOI18N
        jButtonSonucEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSonucEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonSonucEkle)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBoxKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jSpinnerSinavSonucu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerSinavSonucu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButtonSonucEkle)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-button (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initComboBoxs(){
       
      dbIslemleri = new DBIslemleri(veriTabani);
        
      ogrenciler = dbIslemleri.ogrenciGetir();
      kurslar = dbIslemleri.kursGetir();
      
      ogrenciComboBoxModel = new DefaultComboBoxModel(ogrenciler.toArray());
      kursComboBoxModel = new DefaultComboBoxModel(kurslar.toArray());
    
      jComboBoxOgrenci.setModel(ogrenciComboBoxModel);
      jComboBoxKurs.setModel(kursComboBoxModel);
       
      
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
          
        SonuclarUI sonuclarUI = new SonuclarUI();
        
        sonuclarUI.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSonucEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSonucEkleActionPerformed
      
     boolean hata;  
     boolean sonuc;
     
     SinavSonucu sinavSonucu;
     
     Integer ogrenciId;
     Integer kursId;
     
     boolean kursBittiMi;
     
     
     sonucOlusturmaEkraniIslemleri = new SonucOlusturmaEkraniIslemleri(jComboBoxOgrenci,jComboBoxKurs,jSpinnerSinavSonucu);
     
     dbIslemleri = new DBIslemleri(veriTabani);
     
     hata = sonucOlusturmaEkraniIslemleri.hataMesajiOlustur();
        
     if(hata == false){
         
         JOptionPane.showMessageDialog(this,sonucOlusturmaEkraniIslemleri.getMesaj(),"Uyarı", 1);
         
     }else{
         
       ogrenciId = dbIslemleri.kullaniciIdBul((Integer) jComboBoxOgrenci.getSelectedItem());
       kursId = dbIslemleri.kursIdBul(jComboBoxKurs.getSelectedItem().toString());
       int skor = (Integer) jSpinnerSinavSonucu.getValue();
               
      
       kursBittiMi = dbIslemleri.kursBittiMi(ogrenciId, kursId);
       
       if(kursBittiMi){
           
           JOptionPane.showMessageDialog(this,"Bu kurs için zaten 3 sınav girilmiş!!!", "Uyarı", 1);
       }else{
 
       sinavSonucu = sonucOlusturmaEkraniIslemleri.sinavSonucuOlustur(0,ogrenciId ,kursId,skor);
    
       sonuc = dbIslemleri.sonucEkleSQL(sinavSonucu);
         
       if(sonuc == false){
           
            JOptionPane.showMessageDialog(this,"Sınav sonucu eklenemedi.","Bilgilendirme", 1); 
           
       }else{
           
           JOptionPane.showMessageDialog(this,"Sınav sonucu eklendi.","Bilgilendirme", 1);
           
           jComboBoxOgrenci.setSelectedIndex(0);
           jComboBoxKurs.setSelectedIndex(0);
           jSpinnerSinavSonucu.setValue(50);
           
           
       }
       
     }
     
     }
     
        
    }//GEN-LAST:event_jButtonSonucEkleActionPerformed

  

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinavSonucuEklemeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinavSonucuEklemeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinavSonucuEklemeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinavSonucuEklemeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinavSonucuEklemeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSonucEkle;
    private javax.swing.JComboBox<String> jComboBoxKurs;
    private javax.swing.JComboBox<String> jComboBoxOgrenci;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerSinavSonucu;
    // End of variables declaration//GEN-END:variables
}
