/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import EkranIslemleri.SonuclarUIEkranIslemleri;
import SQLIslemleri.DBIslemleri;
import javax.swing.JOptionPane;

/**
 *
 * @author ocak
 */
public class SonuclarUI extends javax.swing.JFrame {
    
    DBIslemleri dbIslemleri;
    
    SonuclarUIEkranIslemleri sonuclarUIEkranIslemleri;
    
    private String veriTabani = "kursprojesiveritabani";
    /**
     * Creates new form Sonuclar
     */
    public SonuclarUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_OgrenciNo = new javax.swing.JTextField();
        jTextField_KursIsmi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOrtalamaSonuc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonYeniOgrenci = new javax.swing.JButton();
        jButtonYeniKurs = new javax.swing.JButton();
        jButtonYeniSinavSonucu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));

        jTextField_OgrenciNo.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_OgrenciNo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kurs Sonucu için öğrenci numarası: ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        jTextField_KursIsmi.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_KursIsmi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kurs Sonucu için kurs adı:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        jTextAreaOrtalamaSonuc.setEditable(false);
        jTextAreaOrtalamaSonuc.setBackground(new java.awt.Color(255, 255, 204));
        jTextAreaOrtalamaSonuc.setColumns(20);
        jTextAreaOrtalamaSonuc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextAreaOrtalamaSonuc.setForeground(new java.awt.Color(255, 51, 51));
        jTextAreaOrtalamaSonuc.setLineWrap(true);
        jTextAreaOrtalamaSonuc.setRows(3);
        jTextAreaOrtalamaSonuc.setWrapStyleWord(true);
        jTextAreaOrtalamaSonuc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kurs Sonucu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 51, 51))); // NOI18N
        jScrollPane2.setViewportView(jTextAreaOrtalamaSonuc);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_OgrenciNo)
                    .addComponent(jTextField_KursIsmi)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_OgrenciNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_KursIsmi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        jButtonYeniOgrenci.setBackground(new java.awt.Color(255, 51, 51));
        jButtonYeniOgrenci.setForeground(new java.awt.Color(255, 255, 255));
        jButtonYeniOgrenci.setText("Yeni Ögrenci Oluştur");
        jButtonYeniOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYeniOgrenciActionPerformed(evt);
            }
        });

        jButtonYeniKurs.setBackground(new java.awt.Color(255, 51, 51));
        jButtonYeniKurs.setForeground(new java.awt.Color(255, 255, 255));
        jButtonYeniKurs.setText("Yeni Kurs Oluştur");
        jButtonYeniKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYeniKursActionPerformed(evt);
            }
        });

        jButtonYeniSinavSonucu.setBackground(new java.awt.Color(255, 51, 51));
        jButtonYeniSinavSonucu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonYeniSinavSonucu.setText("Öğrenci sınav sonucu gir");
        jButtonYeniSinavSonucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYeniSinavSonucuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonYeniOgrenci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonYeniKurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonYeniSinavSonucu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jButtonYeniOgrenci)
                .addGap(26, 26, 26)
                .addComponent(jButtonYeniKurs)
                .addGap(31, 31, 31)
                .addComponent(jButtonYeniSinavSonucu)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonYeniOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYeniOgrenciActionPerformed
        
        OgrenciOlusturmaUI ogrenciOlusturmaUI = new OgrenciOlusturmaUI();
        
          this.setVisible(false);
          
          ogrenciOlusturmaUI.setVisible(true);
        
      
        
    }//GEN-LAST:event_jButtonYeniOgrenciActionPerformed

    private void jButtonYeniKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYeniKursActionPerformed
       
       KursOlusturmaUI kursOlusturmaUI = new KursOlusturmaUI();
       
       kursOlusturmaUI.setVisible(true);
        
       this.setVisible(false);
       
    }//GEN-LAST:event_jButtonYeniKursActionPerformed

    private void jButtonYeniSinavSonucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYeniSinavSonucuActionPerformed
        
        SinavSonucuEklemeUI sinavSonucuEklemeUI = new SinavSonucuEklemeUI();
        
        sinavSonucuEklemeUI.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonYeniSinavSonucuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        sonuclarUIEkranIslemleri = new SonuclarUIEkranIslemleri(jTextField_OgrenciNo,jTextField_KursIsmi);
        
        boolean sorun = sonuclarUIEkranIslemleri.kontrol();
        
        if(sorun == false){

        int ogrenciNumarasi = Integer.valueOf(jTextField_OgrenciNo.getText().toString());
        String kursAdi = jTextField_KursIsmi.getText().toString();
        int kullaniciId;
        int kursId;
        
        double sonuc;
        
        dbIslemleri = new DBIslemleri(veriTabani);
        
        kullaniciId = dbIslemleri.kullaniciIdBul(ogrenciNumarasi);
        kursId = dbIslemleri.kursIdBul(kursAdi);
        
        sonuc = dbIslemleri.ortalamaSonucGoster(kullaniciId,kursId);
        
        if(sonuc == 0){
            
           jTextAreaOrtalamaSonuc.setText("("+String.valueOf(ogrenciNumarasi)+"-"+kursAdi+") için ortalama sonuç bulunamadı.");
            
        }else{
            
             jTextAreaOrtalamaSonuc.setText("("+String.valueOf(ogrenciNumarasi)+"-"+kursAdi+") için ortalama sonuç: "+String.valueOf(sonuc)); 
            
             jTextField_OgrenciNo.setText("");
             jTextField_KursIsmi.setText("");
             
        }
        
      }else{
            
         JOptionPane.showMessageDialog(this,sonuclarUIEkranIslemleri.getMesaj(),"Uyarı", 1);
            
      }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SonuclarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SonuclarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SonuclarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SonuclarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SonuclarUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonYeniKurs;
    private javax.swing.JButton jButtonYeniOgrenci;
    private javax.swing.JButton jButtonYeniSinavSonucu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaOrtalamaSonuc;
    private javax.swing.JTextField jTextField_KursIsmi;
    private javax.swing.JTextField jTextField_OgrenciNo;
    // End of variables declaration//GEN-END:variables
}
